### ISSUE TITLE
NameError: uninitialized constant ActiveAdminAddons::InputBase

### ISSUE THREAD

**Issue by oeil2lynx** [platanus/activeadmin_addons#174]
Hi, 

I've got this error when I run the rake db:schema:load task on this repo : 

https://github.com/lr-agenceweb/rails-starter

I'm trying to migrate it on the edge.

**Comment by ldlsegovia** [comment]
I can run `rake db:schema:load` without problems in your app.
Maybe you need to add the initializer https://github.com/platanus/activeadmin_addons/blob/master/lib/generators/activeadmin_addons/install/templates/initializer.rb

<img width="818" alt="screen shot 2018-02-02 at 17 00 33" src="https://user-images.githubusercontent.com/3026413/35752410-9f364b58-083a-11e8-9561-c7ffc0011fb1.png">

**Comment by matiasgarcia** [comment]
This happens to me when running the generator

```
Exiting
/home/matias/.rvm/gems/ruby-2.4.1@lumint/gems/require_all-2.0.0/lib/require_all.rb:102:in `rescue in block in require_all': Could not require /home/matias/.rvm/gems/ruby-2.4.1@lumint/gems/activeadmin_addons-1.3.0/lib/activeadmin_addons/support/input_base.rb (uninitialized constant ActiveAdminAddons::InputBase::InputOptionsHandler). Please require the necessary files (RequireAll::LoadError)
	from /home/matias/.rvm/gems/ruby-2.4.1@lumint/gems/require_all-2.0.0/lib/require_all.rb:97:in `block in require_all'
	from /home/matias/.rvm/gems/ruby-2.4.1@lumint/gems/require_all-2.0.0/lib/require_all.rb:96:in `each'
	from /home/matias/.rvm/gems/ruby-2.4.1@lumint/gems/require_all-2.0.0/lib/require_all.rb:96:in `require_all'
	from /home/matias/.rvm/gems/ruby-2.4.1@lumint/gems/require_all-2.0.0/lib/require_all.rb:118:in `block in require_rel'
	from /home/matias/.rvm/gems/ruby-2.4.1@lumint/gems/require_all-2.0.0/lib/require_all.rb:117:in `each'
	from /home/matias/.rvm/gems/ruby-2.4.1@lumint/gems/require_all-2.0.0/lib/require_all.rb:117:in `require_rel'
	from /home/matias/.rvm/gems/ruby-2.4.1@lumint/gems/activeadmin_addons-1.3.0/lib/activeadmin_addons/engine.rb:10:in `block in <class:Engine>'
	from /home/matias/.rvm/gems/ruby-2.4.1@lumint/gems/railties-5.1.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/matias/.rvm/gems/ruby-2.4.1@lumint/gems/railties-5.1.1/lib/rails/initializable.rb:30:in `run'
	from /home/matias/.rvm/gems/ruby-2.4.1@lumint/gems/railties-5.1.1/lib/rails/initializable.rb:59:in `block in run_initializers'
	from /home/matias/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
	from /home/matias/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/matias/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/matias/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/matias/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each'
	from /home/matias/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `call'
	from /home/matias/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/matias/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
	from /home/matias/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
```

**Comment by jdaarevalo** [comment]
hi, I have the same error, some help?

**Comment by icapuccio** [comment]
@ldlsegovia I have the same problem too. The error is raised when running the server. I've no problem running `rake db:schema:load`

**Comment by petres-a** [comment]
still an issue..

**Comment by Tranchinhthuc** [comment]
I just resolved this by removing Gemfile.lock, then re-run `bundle install`.

Cheers

**Comment by asadakbar** [comment]
I hit this issue as well. Running `bundle update activeadmin_addons` resolved the issue and updated activeadmin_addons to the latest version.
