### ISSUE TITLE
Using Enumerize 2.0.0 causes a SystemStackError due to infinite recursion on constructing filters

### ISSUE THREAD

**Issue by edave** [platanus/activeadmin_addons#77]
Using [Enumerize](https://github.com/brainspec/enumerize) 2.0.0 sets off an infinite recursion war between ActiveAdmin Addons and Enumerize's efforts to modify Formastic. I believe this is occurring whenever a Filter is constructed, regardless of whether the relevant model uses Enumerize, as all of the index pages in my ActiveAdmin are throwing this error, but the Dashboard is not.

For example, see this stack trace:

```
7:10:48 web.1  | Completed 500 Internal Server Error in 2174ms (ActiveRecord: 4.4ms)
17:10:48 web.1  | 
17:10:48 web.1  | SystemStackError (stack level too deep):
17:10:48 web.1  |   activerecord (4.2.7.1) lib/active_record/dynamic_matchers.rb:37:in `block in match'
17:10:48 web.1  |   activerecord (4.2.7.1) lib/active_record/dynamic_matchers.rb:37:in `each'
17:10:48 web.1  |   activerecord (4.2.7.1) lib/active_record/dynamic_matchers.rb:37:in `find'
17:10:48 web.1  |   activerecord (4.2.7.1) lib/active_record/dynamic_matchers.rb:37:in `match'
17:10:48 web.1  |   activerecord (4.2.7.1) lib/active_record/dynamic_matchers.rb:12:in `respond_to?'
17:10:48 web.1  |   activeadmin_addons (0.9.3) lib/activeadmin_addons/support/enumerize_formtastic_support.rb:13:in `input_with_ransack'
17:10:48 web.1  |   enumerize (2.0.0) lib/enumerize/hooks/formtastic.rb:18:in `input'
17:10:48 web.1  |   activeadmin_addons (0.9.3) lib/activeadmin_addons/support/enumerize_formtastic_support.rb:19:in `input_with_ransack'
17:10:48 web.1  |   enumerize (2.0.0) lib/enumerize/hooks/formtastic.rb:18:in `input'
17:10:48 web.1  |   activeadmin_addons (0.9.3) lib/activeadmin_addons/support/enumerize_formtastic_support.rb:19:in `input_with_ransack'
17:10:48 web.1  |   enumerize (2.0.0) lib/enumerize/hooks/formtastic.rb:18:in `input'
17:10:48 web.1  |   activeadmin_addons (0.9.3) lib/activeadmin_addons/support/enumerize_formtastic_support.rb:19:in `input_with_ransack'
17:10:48 web.1  |   enumerize (2.0.0) lib/enumerize/hooks/formtastic.rb:18:in `input'
17:10:48 web.1  |   activeadmin_addons (0.9.3) lib/activeadmin_addons/support/enumerize_formtastic_support.rb:19:in `input_with_ransack'
17:10:48 web.1  |   enumerize (2.0.0) lib/enumerize/hooks/formtastic.rb:18:in `input'
... and on...
```

This is Enumerize's [Formtastic hook](https://github.com/brainspec/enumerize/blob/master/lib/enumerize/hooks/formtastic.rb) and the [corresponding hook](https://github.com/platanus/activeadmin_addons/blob/master/lib/activeadmin_addons/support/enumerize_formtastic_support.rb) in ActiveAdmin Addons

Unfortunately I don't understand enough about Formtastic to know what's really going on here, but I'm happy to help debug further.

**Comment by gcovolan** [comment]
I have the same problem!

**Comment by rchervin** [comment]
I just encountered this issue as well - I got a stack too deep error with this command repeating itself in the trace:

```
activeadmin_addons (0.9.3) lib/activeadmin_addons/support/enumerize_formtastic_support.rb:19:in `input_with_ransack'
  enumerize (2.0.0) lib/enumerize/hooks/formtastic.rb:18:in `input'
```

**Comment by anthony-robin** [comment]
I have the same error. Is there a clean fix for this issue ?
